### ISSUE TITLE
Picking which SMILES if LipidMap gives more than one SMILES to choose

### ISSUE THREAD

**Issue by JauntyJJS** [BakerLabNCSU/SCOPE#1]
Hi,

I was reading through the script `Odenkirk_Lipid_SMILES.R` and was getting to this part of the code chunk on line 24-28

```
for (i in 1:length(lipids)) {
  call1 <- paste0("https://www.lipidmaps.org/rest/compound/abbrev_chains/", lipids[i],"/smiles/txt")
  get_smiles <- httr::GET(call1)
  get_smiles_text <- httr::content(get_smiles, "text")
  get_smiles_text <- sub(".*smiles\\t(.*)\\n\\n", "\\1", get_smiles_text)
```

I understand that it is possible for `get_smiles` to get more than one SMILES from a given lipid input. Examples are
[PG(16:0_18:2)](https://www.lipidmaps.org/rest/compound/abbrev_chains/PG(16:0_18:2)/smiles) and [TG(18:3_18:3_20:0)](https://www.lipidmaps.org/rest/compound/abbrev_chains/TG(18:3_18:3_20:0)/smiles)

My question is what does `get_smiles_text <- sub(".*smiles\\t(.*)\\n\\n", "\\1", get_smiles_text)` actually do ?
Does it pick the first SMILES or the last SMILES by default ?

Kindly clarify. Thank you.

**Comment by MelOdenkirk** [comment]
The `call1 <- paste0("https://www.lipidmaps.org/rest/compound/abbrev_chains/", lipids[i],"/smiles/txt")` command is a compilation of all LipidMaps smiles, which are compiled as one entry and read in through `get_smiles_text <- httr::content(get_smiles, "text")` for each entry. 

The default of  `get_smiles_text <- sub(".*smiles\\t(.*)\\n\\n", "\\1", get_smiles_text)` is to record the last SMILES entry from this output. This order does not necessarily follow the order database hits might appear in from searching lipids within LipidMaps.
